### ISSUE TITLE
The Euclidean Distance for Grounding Transformer is missing

### ISSUE THREAD

**Issue by chenwang1701** [ZHANGDONG-NJUST/FPT#14]
In GT, there are not Euclidean Distance similarity for Grounding Transformer?

**Comment by ZHANGDONG-NJUST** [comment]
Thanks for your attention. By euclidean distance, you can directly use "F.pairwise_distance (theta_x, phi_x)" instead of  "torch.matmul" in "lib/modeling/grounding_trans.py".

**Comment by 1849615215** [comment]
I also want to ask that whether i should use  -F.pairwise_distance (theta_x, phi_x) ,instead of F.pairwise_distance (theta_x, phi_x)...very thanks
