### ISSUE TITLE
nms_cuda.c: No such file or directory

### ISSUE THREAD

**Issue by coolbay** [ZHANGDONG-NJUST/FPT#15]
I have the following error when compiling the cuda code by running 'bash lib/make.sh'.

gcc: error: lib/model/nms/src/nms_cuda.c: No such file or directory

**Comment by ZHANGDONG-NJUST** [comment]
@coolbay  Thanks for your attention. My suggestion is that if you really don't know how to compile, you can compile another framework, and then merge FPT in. The FPT part does not need to be compiled.

**Comment by coolbay** [comment]
Thanks very much for your reply! 

Could you please also check whether you have included this file 'lib/model/nms/src/nms_cuda.c' in your repository, also for the benefit of other followers? I cannot find it in that directory.

Thanks again!

**Comment by ZHANGDONG-NJUST** [comment]
@coolbay  Yes, sure. Thank you for your advice
