### ISSUE TITLE
Some mismatch between your code and paper

### ISSUE THREAD

**Issue by Dorispaopao** [ZHANGDONG-NJUST/FPT#17]
Where are  the Q and V from in Rendering model?  I think the Q and V in your code come from the same layer,  such as x_high in Rendering_trans.py. But in your paper, the Q and V are marked in different layers.

**Comment by NEUdeep** [comment]
作者能解释一下为什么吗 谢谢

**Comment by ZHANGDONG-NJUST** [comment]
@Dorispaopao @NEUdeep  Thanks for your attention.  In RT, **Q** denotes the high-level feature maps, **K** and **V** are the low-level feature maps.  x_att =  x_high_mask (**Q**)* x_low_gp (**K**),  out = self.bn_upsample(self.conv_upsample(x_high)) (**V**) + x_att)

**Comment by ZHANGDONG-NJUST** [comment]
@NEUdeep @Dorispaopao Sorry for my carelessness. This part of the code has been fixed.
