### ISSUE TITLE
A problem about the LGT

### ISSUE THREAD

**Issue by wangbo-zhao** [ZHANGDONG-NJUST/FPT#18]
I can not find the code for LGT.  And I have a question about the figure3(c) in the original paper, where Xc and Xf have the same size.  Do you use a upsample operation on Xc before doing LGT?
Thanks!

**Comment by ZHANGDONG-NJUST** [comment]
@wangbo-zhao  Thanks for your question. The condition for LGT is that the sizes between two feature maps are the same.  Therefore, there is no need to upsample Xc, otherwise the coordinates between the two feature maps will not correspond.

**Comment by wangbo-zhao** [comment]
Thanks for your reply. So, it means that LGT must be done on two features with the same size. So it is impossible to use FPT with LGT on traditional feature pyramid network(FPN), as shown on Fig2.  But as writen in section FPT for semantic segmentation, it is used on Unscathed Feature Pyramid(UFP). So I guess that all features in UFP are in the same size. Is it right?

**Comment by ZHANGDONG-NJUST** [comment]
@wangbo-zhao  Yes, you are right. LGT is only applicable when the scale of feature maps is the same.

**Comment by wangbo-zhao** [comment]
OK, thank you.
