### ISSUE TITLE
bug in grounding trans

### ISSUE THREAD

**Issue by HopLee6** [ZHANGDONG-NJUST/FPT#2]
`y = y.view(batch_size, self.inter_channels, *x.size()[2:])`

`x` not defined

ps: i always get "out of memory" error in FPT.

**Comment by ZHANGDONG-NJUST** [comment]
Thanks for the report. Have been fixed.
For "out of memory", you can down-sample the feature maps corresponding to K and V by pooling or stride Conv, such that some computation cost can be reduced. Or, you can choose to use part of the transformer methods in your network.
