### ISSUE TITLE
I can't find the codes of UFP

### ISSUE THREAD

**Issue by 1849615215** [ZHANGDONG-NJUST/FPT#20]
srrory,  through reading your paper and codes ,I can't find the codes of UFP ,but I'm eager to know more detail about UFP. can you supply the codes of UFP? thanks very much!!!

**Comment by ZHANGDONG-NJUST** [comment]
@1849615215    UFP is easy to implement, we have not disclosed it here. You can replace each item in the ASPP architecture with GCN, and the parameters do not need to be changed
