### ISSUE TITLE
Can you share your concrete implementation in LGT(Locality-constrained GT)?

### ISSUE THREAD

**Issue by mozhisisheng** [ZHANGDONG-NJUST/FPT#21]
Thanks for your awesome work. The idea in LGT that only a local square area is queried for each query qj is well and easy to understand. My question is that how to implement it efficiently? In Nol-local mechansim, the H and W dimensions of matrix are unfolded and the length of the new dimension is H*W where it's fussy to find the corresponding square area. In issue #19 , you pointed that operating pooling can get the approximate result, what its means? Please explain in detail and preferably provide source code.

**Comment by ZHANGDONG-NJUST** [comment]
@mozhisisheng  Sorry for the confusion. If you don’t mind, you can send me an email at dongzhang@njust.edu.cn. Discussing on the phone may be more efficient ~
