### ISSUE TITLE
Where is the euclidean distance Similarity in GT?

### ISSUE THREAD

**Issue by boykac** [ZHANGDONG-NJUST/FPT#26]
It seems inconsistent with the paper.

**Comment by ZHANGDONG-NJUST** [comment]
Sorry for the confusion. It can be achieved by replacing touch.matmul with torch.dist.

**Comment by ydhongHIT** [comment]
> Sorry for the confusion. It can be achieved by replacing touch.matmul with torch.dist.

Hi, can you update the ground_trans.py to make it consistent with your paper?
