### ISSUE TITLE
How to use FPT

### ISSUE THREAD

**Issue by Z-Zheng** [ZHANGDONG-NJUST/FPT#27]
The input of FPT are res2, res3, res4, res5, but the below codes are unable to run.
```
m = FPT(256)
m.eval()

m(*[torch.rand(1, 256, 64, 64),
   torch.rand(1, 512, 32, 32),
   torch.rand(1, 1024, 16, 16),
   torch.rand(1, 2048, 8, 8),
   ])

```
It caused this error:
line 155, in forward
    self.bn_reduction(self.str_conv3x3(x_low)) + x_att)
RuntimeError: The size of tensor a (16) must match the size of tensor b (8) at non-singleton dimension 3

What are the correct input sizes of FPT?

**Comment by ZHANGDONG-NJUST** [comment]
@Z-Zheng  Thanks for you attention. Before FPT, the input channels should be unified to 256.
