### ISSUE TITLE
Where is FPT used?

### ISSUE THREAD

**Issue by WangDeyu** [ZHANGDONG-NJUST/FPT#3]
I have found FPT class, but I cannot find where is the FPT class initialized and referenced.

**Comment by ZHANGDONG-NJUST** [comment]
Here are two FPT versions provided. One is in FPN.py and the other one is in FPT.py. In the former one, a part of the transformer operations is reduced, because some people reported that they have the "out of memory" problem.  The latter is consistent with the implementation of our paper. You can choose anyone to use.

**Comment by WangDeyu** [comment]
> Here are two FPT versions provided. One is in FPN.py and the other one is in FPT.py. In the former one, a part of the transformer operations is reduced, because some people reported that they have the "out of memory" problem. The latter is consistent with the implementation of our paper. You can choose anyone to use.

That is to say, in current repository, it uses FPN version but not FPT version and we should modify code to use FPT version by ourselves, right?

**Comment by ZHANGDONG-NJUST** [comment]
The current version is also FPT, the name is to distinguish different versions.  Thanks ~

**Comment by ZHANGDONG-NJUST** [comment]
The current version is also FPT, the name is to distinguish different versions. Thanks ~

**Comment by ZHANGDONG-NJUST** [comment]
The current version is also FPT, the name is to distinguish different versions.  You can know the specific operation from the code in FPN.py. Thanks ~

**Comment by WangDeyu** [comment]
> The current version is also FPT, the name is to distinguish different versions. You can know the specific operation from the code in FPN.py. Thanks ~

Okay, I think I've got it. Maybe it will be clearer to explicitly call the FPT class of FPT file and reference it in a updated version.

**Comment by ZHANGDONG-NJUST** [comment]
Very good suggestion, thank you ~
