### ISSUE TITLE
how I can train my own dataset made with labelme?

### ISSUE THREAD

**Issue by imkelt** [ZHANGDONG-NJUST/FPT#30]
Could you please tell me how I can train my own dataset made with labelme?  Where should I modify?

**Comment by ZHANGDONG-NJUST** [comment]
@imkelt  I think the format should be consistent with COCO

**Comment by imkelt** [comment]
Have you trained FPT on your own dataset? Or have you only trained FPT on public datasets?

**Comment by ZHANGDONG-NJUST** [comment]
@imkelt  Only on public dataset.
