### ISSUE TITLE
Question about grounding_trans.py

### ISSUE THREAD

**Issue by YunhaoLee** [ZHANGDONG-NJUST/FPT#4]
Hello, I didn't see the use of the negative value of Euclidean distance in GroundTrans.py. Did I miss anything?

**Comment by ZHANGDONG-NJUST** [comment]
Thanks for your attention. In the current repository, we provide four types of similarity calculation methods, i.e., 'gaussian', 'embedded', 'dot', and 'concatenate'. The negative value of Euclidean distance will be released in the updated version.

**Comment by ZHANGDONG-NJUST** [comment]
Thanks for your attention. In the current repository, we provide four types of similarity calculation methods, i.e., 'gaussian', 'embedded', 'dot', and 'concatenate'. The negative value of Euclidean distance will be released in the updated version.

**Comment by YunhaoLee** [comment]
Ok, thanks for your answer.

**Comment by yuanjunchai** [comment]
How about update of the negative value of Euclidean distance in GroundTrans.py?
