### ISSUE TITLE
GPU Memory Consuming

### ISSUE THREAD

**Issue by Todd-Qi** [ZHANGDONG-NJUST/FPT#5]
Amazing Work! @ZHANGDONG-NJUST 
I try the FPT network defined in [FPT.py](https://github.com/ZHANGDONG-NJUST/FPT/blob/master/lib/modeling/FPT.py), but I got the "out of memory" problem. So I adopt the suggestion you give here https://github.com/ZHANGDONG-NJUST/FPT/issues/2#issuecomment-668956916

The following is my experimental settings:
Network: three-scale standard FPN with only self-transformer in scale3 (the lowest resolution stage)
Input: tensor of size [2，3，512，640]
FPN output: scale1:[2, 8, 512, 640], scale2: [2, 16, 256, 320], scale3: [2, 32, 128, 160]

That's to say, I only add `SelfTrans` on scale3, but the GPU memory is increasing from 933M to 7365M
where `SelfTrans = SelfTrans(in_channels=32, inter_channels=None, mode='dot', dimension=2, bn_layer=True)`

**Comment by ZHANGDONG-NJUST** [comment]
Sorry for the late reply, and thanks for your attention. We did not provide the independent effectiveness analysis for the self-transformer in our main paper.  But you can find the relevant content in the paper "GCNet: Non-local Networks Meet Squeeze-Excitation Networks and Beyond".  From Table 2 (a), one can observe that inserting a non-local module right before the last residual block of c4  (with the size of 100x ) can only increase  2.1M model parameters.  So it is unreasonable that 6432M model parameters are increased when adding self-transformer to your scale3, in particular,  when the pooling operation is used.
