### ISSUE TITLE
Have you tested the effect of FPN+FPT?

### ISSUE THREAD

**Issue by FightStone** [ZHANGDONG-NJUST/FPT#6]
Very outstanding job，I see FPT class forward method has input for resnet2, resnet3, resnet4 and resnet5. Do you have test p2, p3, p4 and p5 (FPN output) for FPT forward input? Looking forward to your reply.

**Comment by FightStone** [comment]
when you update the ‘SelfTrans’ class, it is not compatible in fpn class.

**Comment by ZHANGDONG-NJUST** [comment]
Thanks for your attention and comment. Typos will be fixed asap. I think FPN can be regarded as a special simple case of GT. Therefore, it will be a little redundant to do FPT on FPN. You are welcomed to report the results of such an experiment.
